const A='/assets/';
const categories=[
 {slug:'gypsum-plaster-malta-home-office',name:'Gypsum & plaster',tag:'Shape your space',image:'lights1.jpg',intro:'A considered foundation for walls, ceilings and interiors. Explore gypsum boards, plaster and the accessories that bring every detail together.',items:[['Gypsum boards','BoardeX exterior boards, standard CoreX boards and specialised boards for moisture, fire, acoustic and impact requirements.'],['Plaster','Drywall compounds and internal and external plaster, including cement-based and acrylic finishes.'],['Complete systems','Metal profiles, fasteners, access panels and finishing accessories for drywall and suspended ceilings.']],related:['gypsum-malta-home-office']},
 {slug:'ceiling-tiles-malta',name:'Ceiling tiles',tag:'A different perspective',image:'004_AMF_07Apr17_FS2_1493-Medium.jpg',intro:'Give ceilings a purpose beyond the surface, with finishes for commercial interiors, acoustic comfort and everyday practicality.',items:[['A finish for every setting','Explore PVC, Hera, mineral fibre, metal, gypsum and sonic ceiling tiles.'],['Form meets function','Choose from decorative and functional options, with framing systems and accessories to complement your selected tile.'],['Specialist brands','Evolve imports Knauf AMF and Heradesign ceiling tiles in Malta. Ask our team about the right specification for your space.']]},
 {slug:'flooring',name:'Flooring',tag:'Grounded in good design',image:'13235_Bandol_Raum9.jpg',intro:'From the warmth of timber to practical vinyl and outdoor decking, discover a surface that belongs in your space.',items:[['Indoor living','Vinyl parquet, laminate and wooden flooring offer different finishes and installation options for your home or business.'],['Outdoor spaces','Explore decking and artificial turf for terraces, gardens and outdoor areas.'],['Working environments','Interlocking PVC industrial flooring is available for warehouses, garages and other demanding spaces.']],related:['vinyl-flooring','parquet-flooring','laminate-flooring','decking','artificial-turf']},
 {slug:'wall-decor-malta',name:'Walls',tag:'Surfaces with character',image:'wall-panels3-Medium-960x768.jpg',intro:'Texture, depth and personality. Bring your walls into focus with decorative sheeting, dimensional panels, green walls and wallpaper.',items:[['Decorative sheeting','Fresco marble wall sheeting features a natural stone texture and a glass-fibre backing.'],['Living with texture','Choose from artificial green walls, 3D wall panels and brick or wood panels.'],['Wallpaper','Explore wallpaper designs with our team and find a finish that suits your interior.']],related:['wall-sheeting','green-walls','3d-walls']},
 {slug:'paint-and-membrane-malta',name:'Paint & membrane',tag:'Colour. Protection. Possibility.',image:'Paint-1.jpg',intro:'KRAFT paint systems for interiors, exteriors, wood and metal, alongside membranes and fillers for finishing and protection.',items:[['Interior & exterior paint','Explore a broad colour range and products for different surfaces and performance needs.'],['Wood & metal','A selection of paints, primers, varnishes and anti-corrosion products.'],['Membranes & fillers','Liquid roof membranes and ready-to-use fillers for suitable prepared surfaces. Ask our team for product-specific advice.']],related:['paint-malta','membrane']},
 {slug:'lighting-malta',name:'Lighting',tag:'Set the atmosphere',image:'lights3.jpg',intro:'Light changes how a space feels. Discover ceiling lights that balance practical illumination with a considered interior.',items:[['Ceiling lighting','Spotlights, flush ceiling lamps and rope lights offer different ways to illuminate your room.'],['Find your fit','Speak to our team about lighting options for your space, style and requirements.']]},
 {slug:'insulation-acoustic-solutions',name:'Insulation & acoustics',tag:'Comfort, considered',image:'C2B3233-Pano-Medium.jpg',intro:'Thoughtful solutions for thermal and acoustic comfort, whether your space is under construction or already in use.',items:[['Mineral wool','Knauf mineral wool solutions for wall and ceiling insulation and acoustics.'],['External insulation','Fibran XPS sheets and cappotto systems with KRAFT finishes for external applications.'],['Acoustic treatments','Sonic ceiling tiles and personalised acoustic wall frames offer options for offices, restaurants and other spaces.']],related:['thermal-insulation','acoustic-solutions-malta']}
];
const subcategories=[
 ['gypsum-malta-home-office','Gypsum boards','gypsum-plaster-malta-home-office','Explore standard, moisture-resistant and fire-resistant CoreX boards, specialist A1 and Premium CoreX, and BoardeX exterior sheathing. Metal profiles and accessories complete the system.'],
 ['vinyl-flooring','Vinyl flooring','flooring','Vinyl parquet offers a warm feel, quiet comfort and straightforward care. The source range includes click-on installation. Ask our team to confirm the specification and suitability of your chosen product.'],
 ['parquet-flooring','Parquet flooring','flooring','Wooden flooring brings natural character and a timeless appearance. Evolve’s range includes individually treated boards and a choice of installation methods, depending on the product and subfloor.'],
 ['laminate-flooring','Laminate flooring','flooring','Explore contemporary laminate designs with practical care and installation options for everyday living. Visit the showroom to compare finishes.'],
 ['decking','Decking','flooring','A practical finish for outdoor living. Evolve’s decking range features grooved and brushed surfaces and a selection of colours. Confirm the appropriate product and installation details with our team.'],
 ['artificial-turf','Artificial turf','flooring','Create a green outdoor surface with artificial turf, without the watering and maintenance associated with natural grass. Explore the range at our showroom.'],
 ['wall-sheeting','Wall sheeting','wall-decor-malta','Fresco marble wall sheeting brings natural stone texture to interior and exterior surfaces. Its glass-fibre backing supports flexibility and strength.'],
 ['green-walls','Green walls','wall-decor-malta','Artificial green walls bring the appearance of vertical planting to residential and commercial interiors, without the light and ongoing care required by living plants.'],
 ['3d-walls','3D walls','wall-decor-malta','Add depth with decorative three-dimensional wall panels, from a distinctive feature wall to a more subtle interior finish.'],
 ['membrane','Membrane','paint-and-membrane-malta','KRAFT liquid membrane products are available for suitable flat-roof substrates. Speak with our team about surface preparation, application and the correct system for your roof.'],
 ['paint-malta','KRAFT paint','paint-and-membrane-malta','Explore KRAFT interior and exterior paints, wood and metal coatings, primers and finishing products. Compare colour samples in person and confirm availability with the showroom.'],
 ['thermal-insulation','Thermal insulation','insulation-acoustic-solutions','Explore Knauf mineral wool and external Fibran XPS insulation systems. Our team can help you discuss the requirements of your building and the appropriate product specification.'],
 ['acoustic-solutions-malta','Acoustic solutions','insulation-acoustic-solutions','From mineral wool and acoustic ceiling tiles during construction to wall panels and personalised frames in existing spaces, explore options for acoustic comfort.']
].map(([slug,name,parent,intro])=>({slug,name,parent,intro}));
const subImages={
 'gypsum-malta-home-office':'Gypsum-boards-main.jpg',
 'vinyl-flooring':'FOTO_moderna_vinyl_v_lyn_tile_Metall_Oxidiert_15185131159_Milieu-Bild_2_161216_web-e1532359176826.jpg',
 'parquet-flooring':'13328_13329-Sherry_Raumszene.jpg',
 'laminate-flooring':'FOTO_moderna_laminat_horizon_Suna_Eiche_15133130982_Milieu-Bild_180410_web-e1532358877356.jpg',
 'decking':'IMG_5291-Medium.png',
 'artificial-turf':'artificial-turf2-Medium.jpg',
 'wall-sheeting':'wall-panels3-Medium-960x768.jpg',
 'green-walls':'greenwall1-Medium.jpg',
 '3d-walls':'belconti-resort-norm-Medium.jpg',
 'membrane':'Waterproofing-pic.jpg',
 'paint-malta':'RS-Group-billboard-FINAL-no-text.jpg',
 'thermal-insulation':'fibran-xps-300-insulation-sheet-mpy09t5vw3-300x300.jpg',
 'acoustic-solutions-malta':'C2B3233-Pano-Medium.jpg'
};
subcategories.forEach(s=>s.image=subImages[s.slug]);
const projects=[
 {name:'The Westin Dragonara Resort',type:'Hospitality',id:'westin',cover:'Luxury-Bay-Suite-Two-Bedroom-Low-Res.jpg',images:['Luxury-Bay-Suite-Two-Bedroom-Low-Res.jpg','Luxury-Bay-Suite-Low-Res-2.jpg','Luxury-Bay-Suite-Low-Res-4.jpg','Luxury-Bay-Suite-Low-Res.jpg','Luxury-Bay-Suite-Two-Bedroom-Low-Res-2.jpg'],text:'Finishing works for the luxury Bay Suites, including gypsum, plastering and painting, as described in the client’s testimonial.'},
 {name:'The Beer Kitchen',type:'Hospitality',id:'beer-kitchen',cover:'Beer-Kitchen_6.jpg',images:['Beer-Kitchen_6.jpg','Beer-Kitchen_2.jpg','Beer-Kitchen_3.jpg','Beer-Kitchen_4.jpg','Beer-Kitchen_5.jpg'],text:'A hospitality project from the Evolve portfolio. Explore the original project photography.'},
 {name:'Home projects',type:'Residential',id:'homes',cover:'home-project1_big-Medium.jpg',images:[1,2,3,4,5].map(i=>'home-project'+i+'_big-Medium.jpg'),text:'Residential finishing projects from the Evolve portfolio.'},
 {name:'Cafe Cuba',type:'Hospitality',id:'cafe-cuba',cover:'CAFE-CUBA-05-1.jpg',images:['CAFE-CUBA-05-1.jpg','CAFE-CUBA-09.jpg','CAFE-CUBA-12.jpg','CAFE-CUBA-15.jpg','CAFE-CUBA-04.jpg'],text:'A hospitality project from the Evolve portfolio. Explore the original project photography.'},
 {name:'Vecchia Napoli',type:'Hospitality',id:'vecchia-napoli',cover:'Vecchia-Napoli-Shoot-11-1-scaled.jpg',images:['Vecchia-Napoli-Shoot-11-1-scaled.jpg','Vecchia-Napoli-Shoot-22.jpg','Vecchia-Napoli-Shoot-31.jpg','Vecchia-Napoli-Shoot-41.jpg','Vecchia-Napoli-Shoot-4.jpg','Vecchia-Napoli-Shoot-5.jpg'],text:'A hospitality project from the Evolve portfolio. Explore the original project photography.'},
 {name:'Industrial & commercial projects',type:'Commercial',id:'commercial',cover:'Skyparks-business-centre_big.jpg',images:['Valyou-supermarket-2_big.jpg','Skyparks-business-centre_big.jpg','Santana-Hotel_big.jpg','Maritim-hotel_big.jpg','Malta-international-airport_big.jpg'],text:'Portfolio photographs include Valyou, SkyParks Business Centre, Santana Hotel, Maritim Hotel and Malta International Airport.'}
];
module.exports={A,categories,subcategories,projects};
